blueprint:
  name: "ZHA - Tuya TS004F Rotating Knob - 5 Mode Selector"
  description: >
    Wählt einen von 5 Modi per Drehung des Tuya TS004F Knopfes aus.
    Die aktuelle Auswahl wird durch ein RGB-Indikatorlicht angezeigt.
    Ein kurzer Druck startet das zugehörige Skript.

  domain: automation

  input:
    remote:
      name: Tuya TS004F Rotating Knob
      description: Wähle den Drehknopf.
      selector:
        device:
          integration: zha
          model: TS004F

    indicator_light:
      name: Indikator-Licht
      description: RGB-Leuchte, die den aktuellen Modus anzeigt.
      selector:
        entity:
          domain: light

    mode_helper:
      name: Modus-Speicher (Helper)
      description: input_number zur Speicherung des aktuellen Modus.
      selector:
        entity:
          domain: input_number

    action_1:
      name: Aktion 1
      description: Aktion für Modus 1 (Rot)
      selector:
        action:
      default: []

    action_2:
      name: Aktion 2
      description: Aktion für Modus 2 (Grün)
      selector:
        action:
      default: []

    action_3:
      name: Aktion 3
      description: Aktion für Modus 3 (Blau)
      selector:
        action:
      default: []

    action_4:
      name: Aktion 4
      description: Aktion für Modus 4 (Gelb)
      selector:
        action:
      default: []

    action_5:
      name: Aktion 5
      description: Aktion für Modus 5 (Lila)
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

variables:
  modes:
    0: { name: "Modus 1", color: [0, 100] }      # Rot
    1: { name: "Modus 2", color: [120, 100] }    # Grün
    2: { name: "Modus 3", color: [240, 100] }    # Blau
    3: { name: "Modus 4", color: [50, 100] }     # Gelb
    4: { name: "Modus 5", color: [280, 100] }    # Lila

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input 'remote'

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      mode_helper_entity: !input 'mode_helper'
      current_index: "{{ states(mode_helper_entity) | int(default=0) }}"
      cluster_id: '{{ trigger.event.data.cluster_id }}'
      endpoint_id: '{{ trigger.event.data.endpoint_id }}'
      step_type: >-
        {%- if (trigger.event.data.args|list)|length == 3 -%}
          {%- set args = trigger.event.data.args|list -%}
          {%- if args|first == 0 -%}
            {{ 'right' }}
          {%- elif args|first == 1 -%}
            {{ 'left' }}
          {%- else -%}
            {{ '' }}
          {%- endif -%}
        {%- else -%}
            {{ 'single_press' }}
        {%- endif -%}

  - choose:
      ### Drehung: Modus wechseln ###
      - conditions:
          - '{{ command == "step" }}'
          - '{{ cluster_id == 8 }}'
          - '{{ endpoint_id == 1 }}'
        sequence:
          - variables:
              new_index: >-
                {% if step_type == 'right' %}
                  {{ (current_index + 1) % 5 }}
                {% elif step_type == 'left' %}
                  {{ (current_index - 1) % 5 }}
                {% endif %}
          - service: input_number.set_value
            target:
              entity_id: "{{ mode_helper_entity }}"
            data:
              value: "{{ new_index }}"
          - service: light.turn_on
            target:
              entity_id: !input indicator_light
            data:
              hs_color: "{{ modes[new_index].color }}"
              brightness: 255

      ### Kurzer Druck: Skript starten ###
      - conditions:
          - "{{ command == 'remote_button_short_press' }}"
        sequence:
          - choose:
              - conditions: "{{ current_index == 0 }}"
                sequence: !input action_1
              - conditions: "{{ current_index == 1 }}"
                sequence: !input action_2
              - conditions: "{{ current_index == 2 }}"
                sequence: !input action_3
              - conditions: "{{ current_index == 3 }}"
                sequence: !input action_4
              - conditions: "{{ current_index == 4 }}"
                sequence: !input action_5
          # Bestätigung durch Blinken
          - repeat:
              count: 2
              sequence:
                - service: light.turn_off
                  target:
                    entity_id: !input indicator_light
                - delay: "00:00:0.3"
                - service: light.turn_on
                  target:
                    entity_id: !input indicator_light
                  data:
                    hs_color: "{{ modes[current_index].color }}"
                    brightness: 255
                - delay: "00:00:0.3"
