blueprint:
  name: "ZHA - Tuya TS004F Rotating Knob - Flexible Actions"
  description: >
    Steuerung verschiedener Aktionen mit dem Tuya TS004F Drehknopf.
    Die Drehung wählt eine Aktion aus, die durch ein Indikatorlicht farblich signalisiert wird.
    Die Aktion kann per Knopfdruck ausgeführt werden.

  domain: automation

  input:
    remote:
      name: Tuya TS004F Rotating Knob
      description: Wähle den Drehknopf.
      selector:
        device:
          integration: zha
          model: TS004F

    indicator_light:
      name: Indikator-Licht
      description: Die RGB-Leuchte, die den aktuellen Modus anzeigt.
      selector:
        entity:
          domain: light

    actions:
      name: Aktionen
      description: Definiere Aktionen mit Farben und den dazugehörigen Befehlen.
      selector:
        object:

mode: restart
max_exceeded: silent

variables:
  action_list: !input actions
  action_names: "{{ action_list.keys() }}"
  action_colors: "{{ {key: action_list[key]['color'] for key in action_list} }}"
  action_sequences: "{{ {key: action_list[key]['sequence'] for key in action_list} }}"
  current_index: 0

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"

  - choose:
      ### Auswahl der nächsten Aktion durch Drehung ###
      - conditions:
          - "{{ command == 'left' or command == 'right' }}"
        sequence:
          - variables:
              current_index: >-
                {% if command == 'right' %}
                  {{ (current_index + 1) % action_names | length }}
                {% else %}
                  {{ (current_index - 1) % action_names | length }}
                {% endif %}
              selected_action: "{{ action_names[current_index] }}"
          - service: light.turn_on
            target:
              entity_id: !input indicator_light
            data:
              hs_color: "{{ action_colors[selected_action] }}"

      ### Aktion ausführen durch kurzen Druck ###
      - conditions:
          - "{{ command == 'remote_button_short_press' }}"
        sequence: "{{ action_sequences[selected_action] }}"

      ### Bestätigung durch Doppelklick (Blinkt 2x in der aktuellen Farbe) ###
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input indicator_light
            data:
              hs_color: "{{ action_colors[selected_action] }}"
          - delay: "00:00:01"
          - service: light.turn_off
            target:
              entity_id: !input indicator_light
          - delay: "00:00:50"
          - service: light.turn_on
            target:
              entity_id: !input indicator_light
            data:
              hs_color: "{{ action_colors[selected_action] }}"

