blueprint:
  name: "ZHA - Tuya TS004F Rotating Knob - 5 Mode Selector"
  description: >
    Wählt einen von 5 Modi per Drehung des Tuya TS004F Knopfes aus.
    Die aktuelle Auswahl wird durch ein RGB-Indikatorlicht angezeigt.
    Ein kurzer Druck startet das zugehörige Skript.

  domain: automation

  input:
    remote:
      name: Tuya TS004F Rotating Knob
      description: Wähle den Drehknopf.
      selector:
        device:
          integration: zha
          model: TS004F

    indicator_light:
      name: Indikator-Licht
      description: RGB-Leuchte, die den aktuellen Modus anzeigt.
      selector:
        entity:
          domain: light

    mode_helper:
      name: Modus-Speicher (Helper)
      description: input_number zur Speicherung des aktuellen Modus.
      selector:
        entity:
          domain: input_number

    script_1:
      name: Skript 1
      description: Skript für Modus 1 (Rot)
      selector:
        action:
      default: []

    script_2:
      name: Skript 2
      description: Skript für Modus 2 (Grün)
      selector:
        action:
      default: []

    script_3:
      name: Skript 3
      description: Skript für Modus 3 (Blau)
      selector:
        action:
      default: []

    script_4:
      name: Skript 4
      description: Skript für Modus 4 (Gelb)
      selector:
        action:
      default: []

    script_5:
      name: Skript 5
      description: Skript für Modus 5 (Lila)
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

variables:
  modes:
    0: { name: "Modus 1", color: [0, 100] }      # Rot
    1: { name: "Modus 2", color: [120, 100] }    # Grün
    2: { name: "Modus 3", color: [240, 100] }    # Blau
    3: { name: "Modus 4", color: [50, 100] }     # Gelb
    4: { name: "Modus 5", color: [280, 100] }    # Lila

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      mode_helper_entity: !input mode_helper

  # Setze current_index sicher aus dem mode_helper
  - variables:
      current_index: "{{ states(mode_helper_entity) | int(default=0) }}"

  - choose:
      ### Drehung: Modus wechseln ###
      - conditions:
          - "{{ command == 'left' or command == 'right' }}"
        sequence:
          - variables:
              new_index: >-
                {% if command == 'right' %}
                  {{ (current_index + 1) % 5 }}
                {% else %}
                  {{ (current_index - 1) % 5 }}
                {% endif %}
          - service: input_number.set_value
            target:
              entity_id: "{{ mode_helper_entity }}"
            data:
              value: "{{ new_index }}"
          - service: light.turn_on
            target:
              entity_id: !input indicator_light
            data:
              hs_color: "{{ modes[new_index].color }}"
              brightness: 255

      ### Kurzer Druck: Skript starten ###
      - conditions:
          - "{{ command == 'remote_button_short_press' }}"
        sequence:
          - choose:
              - conditions: "{{ current_index == 0 }}"
                sequence: !input script_1
              - conditions: "{{ current_index == 1 }}"
                sequence: !input script_2
              - conditions: "{{ current_index == 2 }}"
                sequence: !input script_3
              - conditions: "{{ current_index == 3 }}"
                sequence: !input script_4
              - conditions: "{{ current_index == 4 }}"
                sequence: !input script_5
          # Bestätigung durch Blinken
          - repeat:
              count: 2
              sequence:
                - service: light.turn_off
                  target:
                    entity_id: !input indicator_light
                - delay: "00:00:0.3"
                - service: light.turn_on
                  target:
                    entity_id: !input indicator_light
                  data:
                    hs_color: "{{ modes[current_index].color }}"
                    brightness: 255
                - delay: "00:00:0.3"
